In [1]:
from sklearn import datasets
iris = datasets.load_iris()

In [4]:
print(iris.DESCR)

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
  

In [5]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [3]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
from sklearn.model_selection import train_test_split as split
X_train, X_test, y_train, y_test = split(iris.data, iris.target, train_size=0.8)

C:\Users\hiroa\Anaconda3\envs\py27\lib\site-packages\sklearn\model_selection\_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [7]:
import keras
from keras.layers import Dense, Activation

C:\Users\hiroa\Anaconda3\envs\py27\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [8]:
# 入力層：4、隠れ層：32、出力層：3(0～2)
model = keras.models.Sequential()
model.add(Dense(units=32, input_dim=4))
model.add(Activation('relu'))
model.add(Dense(units=3))
model.add(Activation('softmax')) 
model.compile(loss='sparse_categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=100)

Epoch 1/100
120/120 [==============================] - 0s 2ms/step - loss: 1.0708 - acc: 0.6000
Epoch 2/100
120/120 [==============================] - 0s 75us/step - loss: 0.8095 - acc: 0.8250
Epoch 3/100
120/120 [==============================] - 0s 75us/step - loss: 0.7621 - acc: 0.8000
Epoch 4/100
120/120 [==============================] - 0s 67us/step - loss: 0.7333 - acc: 0.7000
Epoch 5/100
120/120 [==============================] - 0s 133us/step - loss: 0.7168 - acc: 0.7333
Epoch 6/100
120/120 [==============================] - 0s 92us/step - loss: 0.6944 - acc: 0.7250
Epoch 7/100
120/120 [==============================] - 0s 75us/step - loss: 0.6812 - acc: 0.7417
Epoch 8/100
120/120 [==============================] - 0s 100us/step - loss: 0.6605 - acc: 0.8750
Epoch 9/100
120/120 [==============================] - 0s 75us/step - loss: 0.6476 - acc: 0.7083
Epoch 10/100
120/120 [==============================] - 0s 50us/step - loss: 0.6380 - acc: 0.7333
Epoch 11/100
120/120 [======

120/120 [==============================] - 0s 50us/step - loss: 0.3290 - acc: 0.9500
Epoch 85/100
120/120 [==============================] - 0s 50us/step - loss: 0.3258 - acc: 0.9667
Epoch 86/100
120/120 [==============================] - 0s 42us/step - loss: 0.3291 - acc: 0.9583
Epoch 87/100
120/120 [==============================] - 0s 50us/step - loss: 0.3226 - acc: 0.9250
Epoch 88/100
120/120 [==============================] - 0s 42us/step - loss: 0.3294 - acc: 0.9500
Epoch 89/100
120/120 [==============================] - 0s 42us/step - loss: 0.3184 - acc: 0.9583
Epoch 90/100
120/120 [==============================] - 0s 42us/step - loss: 0.3207 - acc: 0.9667
Epoch 91/100
120/120 [==============================] - 0s 50us/step - loss: 0.3149 - acc: 0.9667
Epoch 92/100
120/120 [==============================] - 0s 50us/step - loss: 0.3138 - acc: 0.9667
Epoch 93/100
120/120 [==============================] - 0s 42us/step - loss: 0.3107 - acc: 0.9583
Epoch 94/100
120/120 [===========

In [9]:
score = model.evaluate(X_test, y_test, batch_size = 1)
print("正解率(accuracy)=", score[1])

30/30 [==============================] - 0s 2ms/step
正解率(accuracy)= 0.9666666666666667


それぞれのラベルに分類できる確率

In [9]:
import numpy as np
x = np.array([[5.1, 3.5, 1.4, 0.2]])
r = model.predict(x)
r

array([[0.9502326 , 0.0455646 , 0.00420278]], dtype=float32)

どのラベルの確率が高いか

In [10]:
r.argmax()

0